apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: play-kube-postgres
spec:
  serviceName: play-kube-postgres
  replicas: 1
  selector:
    matchLabels:
      app: play-kube-postgres
  template:
    metadata:
      labels:
        app: play-kube-postgres
    spec:
      containers:
        - name: play-kube-postgres
          image: postgres:16.2
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: play-kube-postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: play-kube-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
